#!/bin/bash
#

case $1 in
  status)	[[ ! $2 ]] && { systemctl list-units --all | egrep "^  vpn_*" | awk '{print $1,"\t",$2,$3,$4}'; } || { systemctl status vpn_$2.service; };;
  *)		[[ ! $2 ]] && { echo "missing vpn-name"; exit 1; }
                sudo systemctl daemon-reload
                sudo systemctl $1 vpn_$2.service;;
esac
