#!/bin/bash

switch=$1
step=5
vol_cur=$(amixer -D pulse get Master | grep -E -o '[0-9]{1,3}?%' | head -1 | sed 's/%//')
mute=$(amixer -D pulse get Master | grep -E -o '\[[onf]{2,3}\]' | head -1 | sed 's/\[//; s/\]//')

case $switch in
  up)    vol=$(($vol_cur + $step));;
  down)  vol=$(($vol_cur - $step));;
  mute)  if [ $mute = "on" ]; then
           amixer -D pulse sset Master mute
	   vol=0
         else
           amixer -D pulse sset Master unmute
	   switch="unmute"
	   vol=$vol_cur
         fi;;
esac

[[ $vol -lt 0 ]] && vol=0
[[ $vol -gt 100 ]] && vol=100

if [[ "$switch" != "mute" ]]
then
  amixer -D pulse sset Master $vol%
fi

notify-send "Vol" -h int:value:$vol -a volume -c $switch #-h string:x-canonical-private-synchronous:volume
# update i3blocks
pkill -RTMIN+1 i3blocks
