#!/bin/bash
#

new(){
  i3-msg workspace $(zenity --entry --text="new workspace")
}

list(){
  bak=$IFS
  IFS=$'\n'
  i3-msg workspace $(zenity --list --column=aaa --hide-header --width=270 --height=500 $(for aa in $(i3-msg -t get_workspaces | jq -c '.[]'); do  echo $(echo $aa | jq -M '.name' | tr -d '"'); done) 2>/dev/null) > /dev/null
  IFS=$bak
}

case $1 in
  list|new)	$1;;
  *)		echo 'go home';;
esac

exit 0
